import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@styles/globals.css";
import Navbar from "@components/navbar/navbar";

const inter = Raleway({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex items-center min-h-screen flex-col bg-black">
          {children}
        </main>
      </body>
    </html>
  );
}
